#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $CRON_POSTGRES_USER WITH LOGIN SUPERUSER PASSWORD '$CRON_POSTGRES_VALUE';
EOSQL